const express = require("express");
const router = express.Router();
const { protect } = require("../middleware/authMiddleware");
const User = require("../models/user");
const upload = require("../middleware/uploadMiddleware"); // The new file we created

// GET current user
router.get("/me", protect, async (req, res) => {
  res.json(req.user);
});

// 2. GET user by ID (REQUIRED FOR ANALYSIS PAGE)
router.get("/:id", async (req, res) => {
  try {
    const user = await User.findById(req.params.id).select("fullName email profilePicture");
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }
    res.json(user);
  } catch (err) {
    res.status(500).json({ message: "Server error", error: err.message });
  }
});
// UPDATE profile (Text fields like Name, Bio, etc.)
router.put("/profile", protect, async (req, res) => {
  try {
    const user = await User.findById(req.user._id);

    if (!user) return res.status(404).json({ message: "User not found" });

    // Update text fields
    user.fullName = req.body.fullName || user.fullName;
    user.email = req.body.email || user.email;
    user.phone = req.body.phone || user.phone;
    user.location = req.body.location || user.location;
    user.bio = req.body.bio || user.bio;
    user.institution = req.body.institution || user.institution;

    const updatedUser = await user.save();
    res.json(updatedUser);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// NEW: Route to handle the image upload to Cloudinary
router.post("/upload-avatar", protect, upload.single('profileImage'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ message: "No file uploaded" });
    }

    const user = await User.findById(req.user._id);
    
    // req.file.path is the URL generated by Cloudinary
    user.profilePicture = req.file.path; 
    await user.save();

    res.json({ 
      message: "Image uploaded successfully!", 
      url: user.profilePicture 
    });
    
  } catch (error) {
    console.error("Upload Error:", error);
    res.status(500).json({ message: "Upload failed" });
  }
});

module.exports = router;